debug = true
repo = "postgres://multibot:multibot@postgres:5432/multibot?sslmode=disable"
addr = ":8080"

[cms]
login = "test"
password = "test"
static_dir_path = "/app/static"

[llm]
timeout = "1m"

[[llm.providers]]
addr = "http://localhost:11434"
model = "qwen3:0.6b"
type = "ollama"
timeout = "1m"


[[llm.providers]]
addr = "https://openrouter.ai/api/v1"
model = "deepseek/deepseek-chat-v3.1:free"
token = ""
type = "openai"
