{
 "title": "OlegBot",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   {
    "name": "job",
    "label": "Job",
    "query": {
     "query": "label_values(olegbot_repository_quote_count, job)"
    }
   },
   {
    "name": "node",
    "label": "Host:",
    "query": {
     "query": "label_values(olegbot_repository_quote_count{job=\"$job\"}, instance)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Go",
   "type": "stat",
   "description": "Данные инструментария Go",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "go_goroutines{instance=\"$node\",job=\"$job\"}",
     "legendFormat": "gorutines"
    },
    {
     "expr": "go_threads{instance=\"$node\",job=\"$job\"}",
     "legendFormat": "threads"
    }
   ]
  },
  {
   "title": "Quotes",
   "type": "stat",
   "description": "Количество цитат бота",
   "gridPos": { "h": 4, "w": 2, "x": 3, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "olegbot_repository_quote_count{instance=\"$node\",job=\"$job\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Go memstat",
   "type": "stat",
   "description": "Данные потребления памяти Go",
   "gridPos": { "h": 4, "w": 7, "x": 5, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "go_memstats_alloc_bytes{instance=\"$node\",job=\"$job\"}",
     "legendFormat": "alloc_bytes"
    },
    {
     "expr": "go_memstats_sys_bytes{instance=\"$node\",job=\"$job\"}",
     "legendFormat": "sys_bytes"
    },
    {
     "expr": "go_memstats_heap_alloc_bytes{instance=\"$node\",job=\"$job\"}",
     "legendFormat": "heap_alloc_bytes"
    },
    {
     "expr": "go_memstats_heap_sys_bytes{instance=\"$node\",job=\"$job\"}",
     "legendFormat": "heap_sys_bytes"
    }
   ]
  },
  {
   "title": "Endpoints",
   "type": "timeseries",
   "description": "Количество нагрузки на ендпоинт",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "sum(delta(olegbot_controller_handle_count{instance=\"$node\",job=\"$job\"}[$__rate_interval])) by (endpoint,status)",
     "legendFormat": "{{endpoint}}/{{status}}"
    }
   ]
  },
  {
   "title": "RPS",
   "type": "stat",
   "description": "Количество обновлений сообщений в секунду",
   "gridPos": { "h": 4, "w": 12, "x": 0, "y": 4 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "rate(olegbot_controller_update_count{instance=\"$node\",job=\"$job\"}[$__rate_interval])",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}