name: golang
on: [push]

jobs:
  golang:
    runs-on: ubuntu-latest
    steps:
      # Небольшой костыль для того чтобы сетапер Go не перекачивал каждый раз образ
      - name: Cache golang
        uses: actions/cache@v3
        with:
          key: ${{ runner.os }}-go-cache
          path: |
            /opt/hostedtoolcache/go
            /root/go
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v4
        with:
          go-version: "1.21.5"
      - name: Build
        run: go build ./...
      - name: Unit tests
        run: go test ./...
      - name: Lint
        run: go install github.com/golangci/golangci-lint/cmd/golangci-lint@v1.55.2 && golangci-lint run
